### ISSUE TITLE
Вы забыли проверить права секции

### ISSUE THREAD

**Issue by legendabrn** [LazyAhora/CRC#1]
Добавьте `section->Characteristics & IMAGE_SCN_MEM_READ && section->Characteristics & IMAGE_SCN_MEM_EXECUTE) && !(section->Characteristics & IMAGE_SCN_MEM_WRITE)`

**Comment by colby57** [comment]
резня

**Comment by Ahora57** [comment]
Исправлено + я удалил CRT,чтобы при компиляции код весил меньше и было более удобнее анализировать в иде!
